### ISSUE TITLE
Could not load file or assembly 'SlimDX.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by blargle-ragequit** [Koenvh1/ets2-local-radio#18]
I receive the following dialog when attempting to launch ETS2 Local Radio 1.11.0 and 1.11.1:

![untitled](https://cloud.githubusercontent.com/assets/15690966/24235343/17f8d96e-0f5a-11e7-90e5-a7a6bb165c67.png)

When the Details button is expanded, it states the following: 

System.IO.FileNotFoundException: Could not load file or assembly 'SlimDX.dll' or one of its dependencies. The specified module could not be found.
File name: 'SlimDX.dll'
   at ETS2_Local_Radio_server.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ETS2 Local Radio server
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/ETS2%20Local%20Radio%20server.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

**Comment by Koenvh1** [comment]
Sorry for this late response.

Are you sure that you unzipped the release before opening the ETS2 Local Radio server.exe? 
Otherwise it cannot find the SlimDX.dll file that resides in the same folder.

**Comment by blargle-ragequit** [comment]
I installed from the ETS2.Local.Radio.install.exe file.  This had worked fine for me in the past on another machine.

**Comment by Koenvh1** [comment]
That is odd because the uploaded installer does in fact contain the SlimDX dll. It could be one of the dependencies, but that would be strange, because it did work before (and the dependencies haven't changed). 
Could you uninstall ETS2 Local Radio and install it again? You could also try to manually put the SlimDX.dll in your ETS2 Local Radio installation folder.
[SlimDX.dll](https://github.com/Koenvh1/ets2-local-radio/files/872583/SlimDX.zip)

**Comment by blargle-ragequit** [comment]
I reinstalled and can confirm that the installer did put SlimDX.dll in the folder.  Still doesn't work.  Tried replacing it with the one you linked here and it doesn't work.  It must be one of the dependencies.

**Comment by blargle-ragequit** [comment]
Should I try one of the downloads at https://slimdx.org/download.php and see if that fixes it?  If so, will ETS2 Local Radio work better with a particular one of them?

**Comment by KSundstrom** [comment]
I have the exact same problem.

**Comment by ChrisVanHattem** [comment]
And i had it as well today.
Used to work just fine before.

I was happy to find your SlimDX link, it's working fine now.
Windows Defender SmartScreen was btching about your downloadlink as well.
And the funny thing is, i've got Windows Defender disabled.

I had a problem downloading a map yesterday, so it could be something weird with my computer.
But i'm no computer wizz.

Thanks, your radio is awesome.

**Comment by Koenvh1** [comment]
@ChrisVanHattem Looks like I forgot to include the SlimDX.dll for v1.17.0, it's fixed in v1.17.1

**Comment by kamaradski** [comment]
downloading and installing the .NET 4.0 x86 SlimDX solved it for me. Installing the X64 didn't work

I'm running win10 64bit for the record.

Let me know if you want more system specs in order to narrow down this problem for other users.

**Comment by Fakulla** [comment]
Hello I still have this issue as the OP. Tried the suggestions above but with the same result.

**Comment by Koenvh1** [comment]
Installing https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555 should fix the issue.

**Comment by joaquin13311** [comment]
> Installing https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555 should fix the issue.

@Koenvh1  thxx broo!! ahora puedo jugar gta v con mando :D  ninguna otra pagina me ayudó. gracias.
